print('trabajando con strings en python')
texto = 'hoS primer python YoR44 34 56 ' 
print('uppercase:', texto.upper())
print('lowercase:', texto.lower())
print('capitalize:', texto.capitalize())
print('title:', texto.title())
print('strip:', texto.strip())
print('replace:', texto.replace('primer', 'segundo'))
print('find:', texto.find('Yor'))
print('substring [2:7]:', texto[2:7])
print('length:', len(texto))
print('character at index 4:', texto[4])
print('split:', texto.split())
print('endswith "56":', texto.endswith('56'))
print('startswith "hoS":', texto.startswith('hoS'))
print('count of "o":', texto.count('o'))
print('isalpha for "hoS":', 'hoS'.isalpha())
print('isdigit for "34":', '34'.isdigit())
print('isalnum for "YoR44":', 'YoR44'.isalnum())
print('join with "-":', '-'.join(['hoS', 'primer', 'python']))
print('formatting:', 'El texto es: {}'.format(texto))
print(f'formatted string: El texto es: {texto}')
print('splitlines:', 'Linea1\nLinea2\nLinea3'.splitlines())
print('replace "python" with "Java":', texto.replace('python', 'Java'))
print('count of " ":', texto.count(' '))
print('reverse string:', texto[::-1])
print('isupper for texto:', texto.isupper())
print('islower for texto:', texto.islower())
print('swapcase:', texto.swapcase())



